language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install urllib3 certifi pytz"
# command to run tests
script:
  - "python setup.py install"
  - "python setup.py nosetests"
